sudo: false
language: cpp

notifications:
  email: false

branches:
  only:
    - travis

addons:
  sources: &S
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.5
    - llvm-toolchain-precise-3.6
    - llvm-toolchain-precise-3.7
    - llvm-toolchain-precise-3.8
  packages:
    - g++-multilib
    - lcov
    - zsh


# Info: we use short variable names because this looks better in Travis' web interface
# see "before_script" below
#   B .. $BUILD_METHOD_AND_BUILD_TYPE
#   A .. arch flags for both $CFLAGS and $CXXFLAGS
#   D .. definitions for $CPPFLAGS
env:
  global:
    - B= A= D=
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true
  include:
    - os: linux
      compiler: gcc-4.6 -m32
      env: B=cmake/debug A=-m32
      addons: { apt: { packages: [ "g++-multilib" ] } }
    - os: linux
      compiler: gcc-4.6 -m64
      env: B=cmake/release A=-m64

##
## build script
##

before_script:
  - env
  - export BUILD_METHOD_AND_BUILD_TYPE="$B"
  - export VERBOSE=1
  - export CFLAGS="$A"
  - export CXXFLAGS="$A"
  - export CPPFLAGS="$D"
  - export BUILD_DIR="$TRAVIS_BUILD_DIR/build"
script:
  - env
  - bash "$TRAVIS_BUILD_DIR/.travis.sh"
